# Generated by Django 3.2.14 on 2022-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
