# Generated by Django 3.2.14 on 2022-09-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220904_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ntrp',
            field=models.FloatField(),
        ),
    ]
