# Generated by Django 3.2.14 on 2022-09-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_ntrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ntrp',
            field=models.FloatField(default=None),
        ),
    ]
