# Generated by Django 3.2.14 on 2022-09-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_ntrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ntrp2',
            field=models.FloatField(default=None),
        ),
    ]
