# Generated by Django 3.2.14 on 2022-09-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220905_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ntrp',
            field=models.FloatField(default=None),
        ),
    ]
