# Generated by Django 3.2.14 on 2022-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_ntrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ntrp',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
