# Generated by Django 3.2.14 on 2022-10-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_customuser_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
