# Generated by Django 3.2.14 on 2022-10-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_customuser_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='social',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
